# Generated by Django 4.0.6 on 2022-07-08 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeeFormat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.IntegerField(default=0)),
                ('received_sum', models.IntegerField(default=0)),
                ('date', models.DateField()),
                ('student_name', models.CharField(default='Student Name', max_length=80)),
                ('enrolment_number', models.IntegerField(default=0)),
                ('semester', models.CharField(choices=[('SEM1', 'Semester 1'), ('SEM2', 'Semester 2'), ('SEM3', 'Semester 3'), ('SEM4', 'Semester 4'), ('SEM5', 'Semester 5'), ('SEM6', 'Semester 6'), ('SEM7', 'Semester 7'), ('SEM8', 'Semester 8')], default=('SEM7', 'Semester 7'), max_length=11)),
                ('Stream', models.CharField(default='Stream', max_length=10)),
                ('payment_mode', models.CharField(default='Payment Mode', max_length=10)),
                ('transaction_number', models.BigIntegerField(default=0)),
                ('cheque_date', models.DateField()),
            ],
        ),
    ]
