# Generated by Django 4.0.6 on 2022-07-08 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FeeStructure', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feeformat',
            name='Stream',
        ),
    ]
