# Generated by Django 4.0.6 on 2022-07-08 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FeeStructure', '0002_remove_feeformat_stream'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeformat',
            name='Stream',
            field=models.CharField(default='Stream', max_length=10),
        ),
    ]
