# Generated by Django 4.0.6 on 2022-07-08 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FeeStructure', '0003_feeformat_stream'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeformat',
            name='Stream',
            field=models.CharField(choices=[('ICT', 'Information and Communication Technology'), ('CIVIL', 'Civil'), ('ELE', 'Electrical'), ('CS', 'CS')], default=('ICT', 'Information and Communication Technology'), max_length=10),
        ),
    ]
