# Generated by Django 4.0.6 on 2022-07-08 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FeeStructure', '0004_alter_feeformat_stream'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeformat',
            name='enrolment_number',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='feeformat',
            name='receipt_number',
            field=models.BigIntegerField(default=0),
        ),
    ]
