# Generated by Django 4.0.6 on 2022-07-08 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FeeStructure', '0005_alter_feeformat_enrolment_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeformat',
            name='payment_mode',
            field=models.CharField(choices=[('CHEQUE', 'Cheque'), ('DRAFT', 'Draft'), ('PAYTM', 'Paytm')], default=('PAYTM', 'Paytm'), max_length=10),
        ),
    ]
