# Generated by Django 4.0.6 on 2022-07-08 05:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('FeeStructure', '0006_alter_feeformat_payment_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeformat',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feeformat',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
