# Generated by Django 4.0.6 on 2022-07-08 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FeeStructure', '0007_feeformat_created_on_feeformat_last_modified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feeformat',
            old_name='Stream',
            new_name='stream',
        ),
    ]
