# Generated by Django 4.0.6 on 2022-07-09 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FeeStructure', '0008_rename_stream_feeformat_stream'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeformat',
            name='enrolment_number',
            field=models.CharField(max_length=12),
        ),
    ]
